name: Test that this repo works when it's a template

on:
  push: {}
  pull_request:
  schedule:
    - cron: '49 13 * * *'
  workflow_dispatch:

jobs:
  do_template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: install dependencies
        run: |-
          set -ex
          python -m pip install -U setuptools pip
          pip install -U ansible tox
      - name: test collections and roles can be created
        run: ./test_run.sh
